### ISSUE TITLE
[BUG] Installation not completing.

### ISSUE THREAD

**Issue by luggesexe** [phpservermon/phpservermon#1154]
Hello,
I cannot install phpservermonitoring. I tried to install it, got the installation screen and saved the config file manually after not being able to be created automatically. After that, I only got a white screen. Defined the troubleshooting variable and got the following error.
phpservermonitoring 3.5.2 latest
PHP Version 7.4.25

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "#############". in /var/www/vhosts/.../httpdocs/.../Monitor/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:102 Stack trace: #0 /var/www/vhosts/.../httpdocs/.../Monitor/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get() #1 /var/www/vhosts/.../httpdocs/.../Monitor/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(234): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get() #2 [internal function]: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->Symfony\Component\DependencyInjection\ParameterBag\{closure}() #3 /var/www/vhosts/.../httpdocs/.../Monitor/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(222): preg_replace_callback() #4 /var/www/vhosts/.../httpdocs/ in /var/www/vhosts/.../httpdocs/.../Monitor/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 102

**Comment by luggesexe** [comment]
Solved. The DB-Password cannot have a % in it. It will be interpreted as a variable which then cannot be found.
