### ISSUE TITLE
[BUG] Version 3.5.2 does not work under PHP 8.1

### ISSUE THREAD

**Issue by cperrot** [phpservermon/phpservermon#1232]
**Describe the bug**
White screen.

**To Reproduce**
Install PHP 8.1 and run phpservermon

**Expected behavior**

**Screenshots**
It results in a white screen.

**Version (please complete the following information):**
 - Version 3.5.2
 - PHP 8.1

**Additional context**

**Comment by phpony** [comment]
I'm running PHP Server Monitor v3.5.2 on PHP 8.1.7 for a while now, and it's doing great.

Check your error logs for some modules missing or wrong permissions set.

**Comment by cperrot** [comment]
There is absolutely no log. I put all the settings in PHP to show E_ALL errors and only get a white screen with no indication what it could be. I am running it on Ubuntu 22.04 with PHP 8.1
I narrowed it down to getting the "db"
My version of mysql  Ver 8.0.30-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

**Comment by cperrot** [comment]
It is most definitely the php version. I switch from 7.4.38 to 8.1.11 it phpservermon does not work. This on two different servers.

**Comment by idanka** [comment]
I'm running PHP Server Monitor v3.5.2 on PHP 8.1.12  (Fedora 36)
**Works, but manul klikk update Button = all server offline**

Add config.php define('PSM_DEBUG', true); and error list: 
howto fixit? wrong php or apache settings?
`
Deprecated: Symfony\Component\Config\Resource\ComposerResource implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/phpservermonitor/vendor/symfony/config/Resource/ComposerResource.php on line 19

Deprecated: Symfony\Component\Config\Resource\FileResource implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/phpservermonitor/vendor/symfony/config/Resource/FileResource.php on line 21

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Session::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Session.php on line 129

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Session::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Session.php on line 139

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::open($savePath, $sessionName) should either be compatible with SessionHandlerInterface::open(string $path, string $name): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 41

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::close() should either be compatible with SessionHandlerInterface::close(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 49

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::read($sessionId) should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 57

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::write($sessionId, $data) should either be compatible with SessionHandlerInterface::write(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 65

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::destroy($sessionId) should either be compatible with SessionHandlerInterface::destroy(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 73

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::gc($maxlifetime) should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 81

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::validateId($sessionId) should either be compatible with SessionUpdateTimestampHandlerInterface::validateId(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 89

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::updateTimestamp($sessionId, $data) should either be compatible with SessionUpdateTimestampHandlerInterface::updateTimestamp(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 97

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::open($savePath, $sessionName) should either be compatible with SessionHandlerInterface::open(string $path, string $name): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 34

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::read($sessionId) should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 89

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::write($sessionId, $data) should either be compatible with SessionHandlerInterface::write(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 115

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::destroy($sessionId) should either be compatible with SessionHandlerInterface::destroy(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 140

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::validateId($sessionId) should either be compatible with SessionUpdateTimestampHandlerInterface::validateId(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 69

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler::close() should either be compatible with SessionHandlerInterface::close(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 91

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler::gc($maxlifetime) should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 99

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler::updateTimestamp($sessionId, $data) should either be compatible with SessionUpdateTimestampHandlerInterface::updateTimestamp(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 54

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php on line 134

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php on line 144

Fatal error: Uncaught RuntimeException: Failed to start the session because headers have already been sent by "/var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php" at line 17. in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:150 Stack trace: #0 /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Session.php(57): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #1 /var/www/html/phpservermonitor/src/psm/Service/User.php(99): Symfony\Component\HttpFoundation\Session\Session->start() #2 [internal function]: psm\Service\User->__construct() #3 /var/www/html/phpservermonitor/vendor/symfony/dependency-injection/ContainerBuilder.php(1176): ReflectionClass->newInstanceArgs() #4 /var/www/html/phpservermonitor/vendor/symfony/dependency-injection/ContainerBuilder.php(634): Symfony\Component\DependencyInjection\ContainerBuilder->createService() #5 /var/www/html/phpservermonitor/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet() #6 /var/www/html/phpservermonitor/src/psm/Router.php(225): Symfony\Component\DependencyInjection\ContainerBuilder->get() #7 /var/www/html/phpservermonitor/src/psm/Router.php(86): psm\Router->buildTwigEnvironment() #8 /var/www/html/phpservermonitor/index.php(43): psm\Router->run() #9 {main} thrown in /var/www/html/phpservermonitor/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php on line 150`

**Comment by cperrot** [comment]
These are the errors showing

Deprecated: Function libxml_disable_entity_loader() is deprecated in /var/www/html/phpservermon/vendor/symfony/config/Util/XmlUtils.php on line 54

Deprecated: Function libxml_disable_entity_loader() is deprecated in /var/www/html/phpservermon/vendor/symfony/config/Util/XmlUtils.php on line 68

Deprecated: Function libxml_disable_entity_loader() is deprecated in /var/www/html/phpservermon/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 623

Deprecated: Function libxml_disable_entity_loader() is deprecated in /var/www/html/phpservermon/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 625

Deprecated: Symfony\Component\Config\Resource\ComposerResource implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/phpservermon/vendor/symfony/config/Resource/ComposerResource.php on line 19

Deprecated: Symfony\Component\Config\Resource\FileResource implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/phpservermon/vendor/symfony/config/Resource/FileResource.php on line 21

Deprecated: realpath(): Passing null to parameter #1 ($path) of type string is deprecated in /var/www/html/phpservermon/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 40

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Session::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Session.php on line 129

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Session::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Session.php on line 139

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::open($savePath, $sessionName) should either be compatible with SessionHandlerInterface::open(string $path, string $name): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 41

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::close() should either be compatible with SessionHandlerInterface::close(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 49

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::read($sessionId) should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 57

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::write($sessionId, $data) should either be compatible with SessionHandlerInterface::write(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 65

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::destroy($sessionId) should either be compatible with SessionHandlerInterface::destroy(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 73

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::gc($maxlifetime) should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 81

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::validateId($sessionId) should either be compatible with SessionUpdateTimestampHandlerInterface::validateId(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 89

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::updateTimestamp($sessionId, $data) should either be compatible with SessionUpdateTimestampHandlerInterface::updateTimestamp(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 97

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::open($savePath, $sessionName) should either be compatible with SessionHandlerInterface::open(string $path, string $name): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 32

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::read($sessionId) should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 78

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::write($sessionId, $data) should either be compatible with SessionHandlerInterface::write(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 104

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::destroy($sessionId) should either be compatible with SessionHandlerInterface::destroy(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 129

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler::validateId($sessionId) should either be compatible with SessionUpdateTimestampHandlerInterface::validateId(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php on line 67

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler::close() should either be compatible with SessionHandlerInterface::close(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 91

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler::gc($maxlifetime) should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 99

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler::updateTimestamp($sessionId, $data) should either be compatible with SessionUpdateTimestampHandlerInterface::updateTimestamp(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 54

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php on line 134

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php on line 144

Fatal error: Uncaught RuntimeException: Failed to start the session because headers have already been sent by "/var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php" at line 17. in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:145 Stack trace: #0 /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Session.php(57): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #1 /var/www/html/phpservermon/src/psm/Service/User.php(99): Symfony\Component\HttpFoundation\Session\Session->start() #2 [internal function]: psm\Service\User->__construct() #3 /var/www/html/phpservermon/vendor/symfony/dependency-injection/ContainerBuilder.php(1176): ReflectionClass->newInstanceArgs() #4 /var/www/html/phpservermon/vendor/symfony/dependency-injection/ContainerBuilder.php(634): Symfony\Component\DependencyInjection\ContainerBuilder->createService() #5 /var/www/html/phpservermon/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet() #6 /var/www/html/phpservermon/src/psm/Router.php(225): Symfony\Component\DependencyInjection\ContainerBuilder->get() #7 /var/www/html/phpservermon/src/psm/Router.php(86): psm\Router->buildTwigEnvironment() #8 /var/www/html/phpservermon/index.php(45): psm\Router->run() #9 {main} thrown in /var/www/html/phpservermon/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php on line 145

**Comment by Hobo2k** [comment]
I've the same problem, that cron is not working any more.

**Comment by tbba** [comment]
I can confirm: Install and Cron did not work with PHP > 7.4. Running the Backend (after install) works with even PHP 8.2 here.

**Comment by knobhead** [comment]
@cperrot's stack trace boils down to "headers already sent" – index.php and install.php were inaccessible for me when `'PSM_DEBUG'` was set to `true` in `config.php`. After disabling `'PSM_DEBUG', everything worked again for me on PHP 8.1 and 8.2.

**Comment by Hobo2k** [comment]
For me that won't helped with PSM_Debug = false

**Comment by pekidi** [comment]
@Hobo2k 
in config.php remove whole line:

"define('PSM_DEBUG', 'false or true');"

and you should be fine , tested with php8.1  version

**Comment by Hobo2k** [comment]
The line wasn't there and it's not working.

**Comment by pekidi** [comment]
my config.php file include


define('PSM_DB_HOST', 'xxx.xxx.xxx.xxx');
define('PSM_DB_PORT', 'xxxx');
define('PSM_DB_NAME', 'xxxx');
define('PSM_DB_USER', 'xxxxx');
define('PSM_DB_PASS', 'xxxxx');
define('PSM_DB_PREFIX', 'xxx_');
define('PSM_BASE_URL', '');

and php8.1 moduls
php8.1-apcu/jammy,now 5.1.21+4.0.11-7ubuntu1 amd64 [installed]
php8.1-bcmath/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-cli/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed,automatic]
php8.1-common/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed,automatic]
php8.1-curl/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-fpm/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-gd/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-imagick/jammy,now 3.6.0-4ubuntu1 amd64 [installed]
php8.1-intl/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-ldap/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-mbstring/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-mysql/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-opcache/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed,automatic]
php8.1-pspell/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-readline/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed,automatic]
php8.1-soap/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-xml/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1-zip/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 amd64 [installed]
php8.1/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 all [installed]

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by psohm** [comment]
i removed log and it worked
but it would be sad to loose php server monitor when a newer version of php is out
it would be nice to upgrade it in order to remove depandancy

**Comment by mklemme1** [comment]
I just installed PSM as a test with PHP 8.1.2 directly on Ubuntu, no Docker.
PHP deprecation warnings are switched off.

1. `install.php` shows a white screen, without traces in the Apache error log.
2. I created `config.php` manually.
3. The installer then thinks that I use PHP 5 and should "update" to PHP 7.
4. Otherwise, PSM starts without issues.



![install_PHP_warning](https://github.com/phpservermon/phpservermon/assets/3100268/27e65e91-fb86-467c-b6cb-df5d4aab10cf)

I updated PHP to  8.2.12.
Then the installer message is not shown any more.

**Comment by ttg-wolfhoel** [comment]
I added 

`define('PSM_DEBUG', false);
define('PSM_DB_PORT', '3306');`

in config.php. Now it works even with PHP 8.3

**Comment by sebezahn** [comment]
Just a hot fix for cron running over calling status.cron.php with http or https:

PHP 8.3

In cron/status.cron.php line 44 runs into an error:
$data = @unserialize(PSM_CRON_ALLOW);

replace it with:
$data = false;

Script will run again.
