### ISSUE TITLE
500 Error on ?&=server_update clueless

### ISSUE THREAD

**Issue by txj-xyz** [phpservermon/phpservermon#714]
It appears I'm getting a 500 error when attempting to update

```[Tue Mar 19 21:56:04.562148 2019] [:error] [pid 6196] [client 174.52.224.50:50049] 

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/phpservermon-3.1.1/src/includes/functions.inc.php:277
Stack trace:

#0 /var/www/html/phpservermon-3.1.1/src/psm/Util/Server/Updater/StatusUpdater.class.php(179): psm_curl_get('http://192.227....', true, false, 5)

#1 /var/www/html/phpservermon-3.1.1/src/psm/Util/Server/Updater/StatusUpdater.class.php(96): psm\\Util\\Server\\Updater\\StatusUpdater->updateWebsite(2)

#2 /var/www/html/phpservermon-3.1.1/src/psm/Util/Server/UpdateManager.class.php(84): psm\\Util\\Server\\Updater\\StatusUpdater->update('2')

#3 /var/www/html/phpservermon-3.1.1/src/psm/Module/Server/Controller/UpdateController.class.php(45): psm\\Util\\Server\\UpdateManager->run()

#4 /var/www/html/phpservermon-3.1.1/src/psm/Module/AbstractController.class.php(187): psm\\Module\\Server\\Controller\\UpdateController->executeIndex()

#5 /var/www/html/phpservermon-3.1.1/src/psm/Module/AbstractController.class.php(156): psm\\Module\\AbstractController->initializeAction('index')

#6 /var/www/html/phpserver in /var/www/html/phpservermon-3.1.1/src/includes/functions.inc.php on line 277```

**Comment by TimZ99** [comment]
Please check if Curl is installed on your server.

**Comment by TimZ99** [comment]
Hopefully, [this](https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init) will help.
