### ISSUE TITLE
All servers gone after update from 3.2 to 3.4.1

### ISSUE THREAD

**Issue by qx54** [phpservermon/phpservermon#778]
Hi,

After updating from 3.2 to 3.4.1 all servers are gone from the servers and status tabs.

I can see that the servers are still in the database though. Type of all servers is website, but the request_method as well as other table rows are empty. Maybe this is the root cause, because I don't remember I had to select a request method in version 3.2?

PS In debug mode I see:
```
Warning: constant(): Couldn't find constant PSM_DB_PORT in /home/httpd/vhosts/xyz/xyz/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 536
Warning: SQL error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.website_username' in 'field list' in /home/httpd/vhosts/xyz/xyz/src/psm/Service/Database.php on line 544 
```

**Comment by qx54** [comment]
I tried adding a new server but only got a bunch of warnings and errors:

```
Warning: constant(): Couldn't find constant PSM_DB_PORT in /home/httpd/vhosts/xyz/xyz/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 536
Warning: SQL error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'psm_servers.website_username' in 'field list' in /home/httpd/vhosts/xyz/xyz/src/psm/Service/Database.php on line 544
Warning: SQL error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.website_username' in 'field list' in /home/httpd/vhosts/xyz/xyz/src/psm/Service/Database.php on line 544
Fatal error: Uncaught Error: Call to a member function fetchAll() on boolean in /home/httpd/vhosts/xyz/xyz/src/psm/Service/Database.php:132 Stack trace:
#0 /home/httpd/vhosts/xyz/xyz/src/psm/Module/Server/Controller/AbstractServerController.php(98): psm\Service\Database->query('SELECT\n\t\t\t\t\t`s`...')
#1 /home/httpd/vhosts/xyz/xyz/src/psm/Module/Server/Controller/ServerController.php(102): psm\Module\Server\Controller\AbstractServerController->getServers()
#2 /home/httpd/vhosts/xyz/xyz/src/psm/Module/AbstractController.php(193): psm\Module\Server\Controller\ServerController->executeIndex()
#3 /home/httpd/vhosts/xyz/xyz/src/psm/Module/Server/Controller/ServerController.php(367): psm\Module\AbstractController->runAction('index')
#4 /home/httpd/vhosts/xyz/xyz/src/psm/Module/AbstractController.php(193): psm\Module\Server\Controller\ServerController->ex in /home/httpd/vhosts/xyz/xyz/src/psm/Service/Database.php on line 132 
```

**Comment by qx54** [comment]
I compared the DB tables with the upgrades in src/psm/Util/Install/Installer.php

It seems the upgrade for the v3.2.0 release was not applied when I updated to 3.2.0.

How can I re-run `upgrade320()` so the DB gets upgraded?

**Comment by qx54** [comment]
I set the version to 3.1.0 in the DB and re-run install.php

Now the DB seems to be ok and the servers appear again.
